// settings-keys.enum.ts
export enum SettingsKey {
    PLEMIONA_COOKIES = 'PLEMIONA_COOKIES',
    AUTO_SCAVENGING_ENABLED = 'AUTO_SCAVENGING_ENABLED',
    /** Premium mass scavenging (scavenge_mass) — separate from classic per-village scavenging */
    AUTO_SCAVENGING_MASS_ENABLED = 'AUTO_SCAVENGING_MASS_ENABLED',
    AUTO_CONSTRUCTION_QUEUE_ENABLED = 'AUTO_CONSTRUCTION_QUEUE_ENABLED',
    CRAWLER_ORCHESTRATOR_ENABLED = 'CRAWLER_ORCHESTRATOR_ENABLED',
    CRAWLER_ORCHESTRATOR_MONITORING_ENABLED = 'CRAWLER_ORCHESTRATOR_MONITORING_ENABLED',
    MINI_ATTACKS_ENABLED = 'MINI_ATTACKS_ENABLED',
    CLERK_SECRET_KEY = 'CLERK_SECRET_KEY',
    CLERK_PUBLISHABLE_KEY = 'CLERK_PUBLISHABLE_KEY',
    MINI_ATTACKS_VILLAGE_ID = 'MINI_ATTACKS_VILLAGE_ID',
    /** @deprecated Prefer ORCHESTRATOR_SCHEDULING_CONFIG JSON; still read for backward compatibility */
    MINI_ATTACKS_MIN_INTERVAL = 'MINI_ATTACKS_MIN_INTERVAL',
    /** @deprecated Prefer ORCHESTRATOR_SCHEDULING_CONFIG JSON; still read for backward compatibility */
    MINI_ATTACKS_MAX_INTERVAL = 'MINI_ATTACKS_MAX_INTERVAL',
    AUTO_ARMY_TRAINING_LIGHT_ENABLED = 'AUTO_ARMY_TRAINING_LIGHT_ENABLED',
    /** @deprecated Prefer ORCHESTRATOR_SCHEDULING_CONFIG JSON; still read for backward compatibility */
    ARMY_TRAINING_MIN_INTERVAL = 'ARMY_TRAINING_MIN_INTERVAL',
    /** @deprecated Prefer ORCHESTRATOR_SCHEDULING_CONFIG JSON; still read for backward compatibility */
    ARMY_TRAINING_MAX_INTERVAL = 'ARMY_TRAINING_MAX_INTERVAL',
    PLAYER_VILLAGE_ATTACKS_ENABLED = 'PLAYER_VILLAGE_ATTACKS_ENABLED',
    TW_DATABASE = 'TW_DATABASE',
    AUTO_ACCOUNT_MANAGER_ENABLED = 'AUTO_ACCOUNT_MANAGER_ENABLED',
    /** Unified JSON blob for orchestrator task intervals (minutes in patch); see orchestrator-scheduling.types */
    ORCHESTRATOR_SCHEDULING_CONFIG = 'ORCHESTRATOR_SCHEDULING_CONFIG',
}
