// settings-keys.enum.ts
export enum SettingsKey {
    PLEMIONA_COOKIES = 'PLEMIONA_COOKIES',
    AUTO_SCAVENGING_ENABLED = 'AUTO_SCAVENGING_ENABLED',
    AUTO_CONSTRUCTION_QUEUE_ENABLED = 'AUTO_CONSTRUCTION_QUEUE_ENABLED',
    CRAWLER_ORCHESTRATOR_ENABLED = 'CRAWLER_ORCHESTRATOR_ENABLED',
    CRAWLER_ORCHESTRATOR_MONITORING_ENABLED = 'CRAWLER_ORCHESTRATOR_MONITORING_ENABLED',
    MINI_ATTACKS_ENABLED = 'MINI_ATTACKS_ENABLED',
    CLERK_SECRET_KEY = 'CLERK_SECRET_KEY',
    CLERK_PUBLISHABLE_KEY = 'CLERK_PUBLISHABLE_KEY',
    MINI_ATTACKS_VILLAGE_ID = 'MINI_ATTACKS_VILLAGE_ID',
    MINI_ATTACKS_MIN_INTERVAL = 'MINI_ATTACKS_MIN_INTERVAL',
    MINI_ATTACKS_MAX_INTERVAL = 'MINI_ATTACKS_MAX_INTERVAL',
    AUTO_ARMY_TRAINING_LIGHT_ENABLED = 'AUTO_ARMY_TRAINING_LIGHT_ENABLED',
    ARMY_TRAINING_MIN_INTERVAL = 'ARMY_TRAINING_MIN_INTERVAL',
    ARMY_TRAINING_MAX_INTERVAL = 'ARMY_TRAINING_MAX_INTERVAL',
    PLAYER_VILLAGE_ATTACKS_ENABLED = 'PLAYER_VILLAGE_ATTACKS_ENABLED',
    TW_DATABASE = 'TW_DATABASE',
}
