// settings-keys.enum.ts
export enum SettingsKey {
    PLEMIONA_COOKIES = 'PLEMIONA_COOKIES',
    AUTO_SCAVENGING_ENABLED = 'AUTO_SCAVENGING_ENABLED',
    AUTO_CONSTRUCTION_QUEUE_ENABLED = 'AUTO_CONSTRUCTION_QUEUE_ENABLED',
    CRAWLER_ORCHESTRATOR_ENABLED = 'CRAWLER_ORCHESTRATOR_ENABLED',
    // dodawaj kolejne ustawienia tutaj
}
